spring.application.name=portone

# db
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:mysql://localhost:3306/portone
spring.datasource.username=root
spring.datasource.password=heribio!23
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

# portone
portone.pg.provider=uplus
portone.shop.id=imp72371132
portone.api.key=2014851407158823
portone.api.secret=P9nn1ftR3CNTJk28zpVkfN4s8bC16WaBtjIHjOZwZKA20bX21e4I3UB216MnHqRySOD0FMckjX1jaHRk